12. Адаптивная сетка для страницы каталога
htmlacademy-adaptive/1005163-pognali-21 pull request #10
Opened 2020-12-04 07:31 UTC by iShangareev

2020-12-04 09:27 UTC, mikhin requested changes

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/alphabet-wrapper.scss
> +  display: table-cell;
Брррр, такого не должны хотеть)

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/alphabet-wrapper.scss
> +  .alphabet-wrapper__list_big .alphabet-wrapper__item {
У нас же препроцессор, давай сделаем через вложенность через &?

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/alphabet-wrapper.scss
> +    display: none;
Вроде говорили или нет? Что блок не должен хотеть сам себя скрывать

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/countries-list.scss
> +    margin: 0;
А это зачем?

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/filter-wrapper.scss
> +    max-width: 285px;
А это точно от самого блока зависит по дизайну? А не от места куда он вписан?

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/home-button.scss
> +  display: none;
Да, вот видно почему скрытие самого блока это неправильно. А если в другом месте потребуется сделать наоборт, в мобильных показать, а в планшетах скрыть, как будешь решать?)

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/public-card-profile.scss
> +
Лишняя строка

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/public-card-profile.scss
> +    grid-template-areas:
Ой, а нам рили нужна такая сложная сетка?

2020-12-04 09:27 UTC, mikhin commented on source/sass/blocks/regions-list.scss
> +  display: none;
Вот уже и пошла путаница со скрытиями и модификациями. Код уже стал необоснованно сложным. Давай за скрытие/показывание будут отвечать БЭМ-миксы?

2020-12-04 12:48 UTC, iShangareev commented on source/sass/blocks/countries-list.scss
> +    margin: 0;
my bad)

2020-12-04 12:51 UTC, iShangareev commented on source/sass/blocks/home-button.scss
> +  display: none;
модификэйшоном)

2020-12-04 12:53 UTC, iShangareev commented on source/sass/blocks/public-card-profile.scss
> +    grid-template-areas:
Да, там такая сетка наркоманская, подругому можно но там еще больше кода плодить придется, хотя если подскажешь как сделать проще я поменяю, no problem)

2020-12-05 19:36 UTC, mikhin requested changes

2020-12-05 19:36 UTC, mikhin commented on source/sass/blocks/regions-list.scss
> +.regions-list-condition {
Это другой БЭМ-блок или элемент текущего блока?

2020-12-05 19:36 UTC, mikhin commented on source/sass/blocks/regions-list.scss
> +    display: none;
Давай обсудим эту проблему? Я о ней писал ранее)

2020-12-05 19:36 UTC, mikhin commented on source/sass/blocks/public-card-profile.scss
> +      "public-card-profile__photo-pofile public-card-profile__online-status public-card-profile__user-name public-card-profile__list  public-card-profile__list "
Знаешь я что подумал: что в БЭМе нет указаний насчет именования грид-секций, а это значит что мы в праве подумать о том, как улучшить читабельность данного правила.

2020-12-05 19:36 UTC, mikhin commented on source/sass/blocks/page-margin.scss
> +  .page-margin_companions {
этот блок не должен хотеть знать про каких-то компаньенов

2020-12-05 19:36 UTC, mikhin commented on source/sass/blocks/home-button.scss
> +.home-button_hidden {
Непонятно почему в модификаторе хайден описано столько правил

2020-12-05 19:36 UTC, mikhin commented on source/sass/blocks/filter-wrapper.scss
> +    max-width: 285px;
м?)

2020-12-05 19:36 UTC, mikhin commented on source/sass/blocks/countries-list.scss
> +  display: none;
В целом проблема по всему проекту осталась

2020-12-05 19:36 UTC, mikhin commented on source/sass/blocks/alphabet-wrapper.scss
> +    &__list_big {
Не,  я имел ввиду другое. Такая запись ухудшает читабельность кода и нарушает критерий курса.

2020-12-07 06:48 UTC, iShangareev commented on source/sass/blocks/page-margin.scss
> +  .page-margin_companions {
Переименовал в элемент родителя

2020-12-07 06:48 UTC, iShangareev commented on source/sass/blocks/home-button.scss
> +.home-button_hidden {
Убрал лишние стили из модификатора

2020-12-07 06:48 UTC, iShangareev commented on source/sass/blocks/countries-list.scss
> +  display: none;
непонятно

2020-12-07 07:45 UTC, iShangareev commented on source/sass/blocks/public-card-profile.scss
> +      "public-card-profile__photo-pofile public-card-profile__online-status public-card-profile__user-name public-card-profile__list  public-card-profile__list "
переименовать грид блоки

2020-12-07 08:01 UTC, iShangareev commented on source/sass/blocks/regions-list.scss
> +    display: none;
миксуем под родителя

2020-12-07 11:31 UTC, iShangareev commented on source/sass/blocks/alphabet-wrapper.scss
> +    &__list_big {
сделать проще, ненужно много вложенности

2020-12-07 17:42 UTC, merged