13. Доверстать главную страницу
htmlacademy-adaptive/1005163-pognali-21 pull request #11
Opened 2020-12-15 12:00 UTC by iShangareev

2020-12-15 16:05 UTC, mikhin requested changes

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/rate-tariff.scss
> +    left: 86%;
Давай во всем проекте пока что не использовать процены, а использовать пиксели)

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/rate-tariff.scss
> +.rate-tariff__item:nth-child(2)::after {
Это все нужно убрать под амперсанд

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/rate-tariff.scss
> +.rate-tariff__item:nth-child(2)::after {
И докинуть БЭМ-модификаторы, потому что сейчас по коду непонятно для чего это нужно и что происходит)

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/rate-tariff.scss
> +.rate-tariff__item:nth-child(2)::after {
Касается всех таких мест в проекте)

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/section-position.scss
> +.section-position_40 {
Ой, вот такие модификаторы прям очень некруто. Кажется, что это просто прибивание гвоздями под пиксель-перфект. Так и не долго появится классу  `.section-position_41`. Это всё нужно упростить либо в сторону придумывания функционального нейминга, либо переносу этих правил на миксующие элементы.

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/short-info.scss
> +  padding-left: 8px;
А это точно по сути padding а не margin?

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/social-list.scss
> +.social-list_theme_yellow .social-list__item {
Правильный селектор, но давай уберем под амперсанд

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/step-list.scss
> +  counter-reset: section;
👍

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/step-list.scss
> +.step-list__item::after {
Под амперсанд, давай сделаем во всем проекте)

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/step-list.scss
> +    min-height: 280px;
Это точно нужно на БЭМ-блоке, а не на БЭМ-миксе?

2020-12-15 16:05 UTC, mikhin commented on source/sass/blocks/step-list.scss
> +    border-radius: 20px 20px 20px 20px;
Можно написать просто `20px`

2020-12-15 16:06 UTC, mikhin commented
![Снимок экрана 2020-12-15 в 18 53 29](https://user-images.githubusercontent.com/38258318/102240110-8fd01880-3f08-11eb-8e0b-74142b46aaf3.png)
![Снимок экрана 2020-12-15 в 18 54 31](https://user-images.githubusercontent.com/38258318/102240126-93639f80-3f08-11eb-9884-c27c326c2129.png)

Вот тут элементы поехали

2020-12-15 16:06 UTC, mikhin commented
![Снимок экрана 2020-12-15 в 18 54 24](https://user-images.githubusercontent.com/38258318/102240190-a0808e80-3f08-11eb-9c01-5b7c80bdb98d.png)

Вот тут флажки получились мыльные

2020-12-16 06:06 UTC, iShangareev commented on source/index.html
> +                class="promo-board-list__contact-button promo-board-list__button-mail button"
Хотел сначала общие свойства засунуть в баттон потом передумал походу дела

2020-12-16 06:13 UTC, iShangareev commented on source/index.html
> +            главный редактор<br class="promo-board__quote-mobile-indent" />
Вобщем тут такое дело, я сам не хотел использовать, обычно я подгоняют все шириной, но тут в академии сказали мол надо бр делать, может оставим в рамках курса?

2020-12-16 06:25 UTC, iShangareev commented on source/sass/blocks/companion-card.scss
> +  top: -9px;
https://prnt.sc/w3okw8 это для флажков стран сначала убираются стили ul а потом подгоняется по высоте

2020-12-16 07:27 UTC, iShangareev commented on source/sass/blocks/contacts-address.scss
> +    padding-top: 23px;
больше трех значение и обнуления обьединил в одно свойство, по 2 значения оставил

2020-12-16 07:40 UTC, iShangareev commented on source/sass/blocks/contacts-address.scss
> +    display: inline;
это косяк

2020-12-16 08:06 UTC, iShangareev commented on source/sass/blocks/contacts-address.scss
> +      top: -30px;
там при добавлении контента или увеличении ширины контейнера значек ехать начинает

2020-12-16 08:56 UTC, iShangareev commented on source/sass/blocks/direction-card.scss
> +  top: -11px;
Почему?

2020-12-16 09:24 UTC, iShangareev commented on source/sass/blocks/direction-card.scss
> +  left: 57px;
исправл на margin

2020-12-16 10:25 UTC, iShangareev commented on source/sass/blocks/button-detail.scss
> +  position: absolute;
Не совсем понял, исправил места где блоки ехали изначально хотел сделать резиново но потом забил, а так в целом пока нет мыслей как сделать по другому точнее есть но они трудозатратнее

2020-12-16 11:17 UTC, iShangareev commented on source/sass/blocks/contacts-address.scss
> +    max-width: 1200px;
Не, тут ширина нестандартная и блок смещен

2020-12-16 12:15 UTC, iShangareev commented on source/sass/blocks/rate-tariff.scss
> +    top: -13px;
подругому не спозицонируешь, если только в bckg засунуть

2020-12-17 06:25 UTC, iShangareev commented on source/sass/blocks/short-info.scss
> +  padding-left: 8px;
в нашем случае да т.к везде он немного левее находится

2020-12-17 06:27 UTC, iShangareev commented on source/sass/blocks/social-list.scss
> +.social-list_theme_yellow .social-list__item {
тут не получится убрать под амперсант потому что по названию не совпадет амперсант, просто у элемента social-list__item в одном месте есть желтый бэкграунд а в другом месте нету

2020-12-17 06:29 UTC, iShangareev commented on source/sass/blocks/step-list.scss
> +    min-height: 280px;
думаю бэм микс будет лишним в нашем случае

2020-12-17 07:26 UTC, iShangareev commented on source/sass/blocks/button-detail.scss
> +  position: absolute;
На последнем скрине где мыльные флажки позже поменяю там урок по этой тебе как раз будет

2020-12-17 16:30 UTC, mikhin requested changes

2020-12-17 16:30 UTC, mikhin commented on source/index.html
> +              alt="Кнопка закрыть меню"
Не может быть, что элемент по сути картинка, а написано «кнопка» =)

2020-12-17 16:30 UTC, mikhin commented on source/index.html
> +      <section class="companion-travel companion-travel_position">
Непонятно в чем функция модификатора «позишн»

2020-12-17 16:30 UTC, mikhin commented on source/index.html
> +            <li class="rate-tariff__item rate-tariff__item_basic">
непонятно в чем суть функции модификатора «бейсик»

2020-12-17 16:30 UTC, mikhin commented on source/index.html
> +      <section class="companion-travel companion-travel_position">
касается всех подобных модификаторов на всей страницы

2020-12-17 16:30 UTC, mikhin commented on source/sass/blocks/page-margin.scss
> +    margin: 0 auto;
А почему в мобильных это не нужно?

2020-12-17 16:30 UTC, mikhin commented on source/sass/blocks/section-position.scss
>      margin-bottom: -60px;
На БЭМ-блоке не могут висеть правила внешней геометрии

2020-12-17 16:30 UTC, mikhin commented on source/sass/blocks/step-list.scss
> +  &::after {
Нужен отступ в строку

2020-12-17 16:30 UTC, mikhin commented on source/sass/blocks/section-position.scss
>      margin-bottom: -60px;
касается всех БЭМ-блоков и их модификаторов в проекте)

2020-12-17 16:30 UTC, mikhin commented on source/sass/blocks/step-list.scss
> +  &::after {
касается всех подобных моментов во всем проекте

2020-12-17 16:30 UTC, mikhin commented on source/sass/blocks/step-list.scss
> +    font-style: normal;
А это зачем?)

2020-12-17 16:30 UTC, mikhin commented on source/sass/blocks/step-list.scss
>    .step-list__item:last-child {
Давай уберем под амперсанд, и все подобные случаи в проекте

2020-12-18 06:16 UTC, iShangareev commented on source/index.html
> +              alt="Кнопка закрыть меню"
Ахах, да я что то херню сделал)) там же картинка то и не нужна))

2020-12-18 06:24 UTC, iShangareev commented on source/sass/blocks/page-margin.scss
> +    margin: 0 auto;
Изначально стояло для все разрешений ты написал типа если нет ширины то margin: 0 auto; будет там лишним, я расфасовал margin: 0 auto; везде где указаны ширины хотя по сути для margin: 0 auto; необязательно должна быть указана ширина, https://prnt.sc/w555li , давай так оставим)

2020-12-18 06:27 UTC, iShangareev commented on source/sass/blocks/step-list.scss
> +    font-style: normal;
Лишнее, убрал)

2020-12-18 06:49 UTC, iShangareev commented on source/index.html
> +            <li class="rate-tariff__item rate-tariff__item_basic">
Согласен модфикатор не подходит сюда, поменял на микс

2020-12-18 11:17 UTC, mikhin approved these changes

2020-12-18 11:17 UTC, mikhin commented on source/index.html
> +      <section class="direction-travel page__direction-travel">
Клево! Еще в таких случаях можно завести БЭМ-блок `index-page` или `index-page-layout` и позиционировать элементы от него. Потому что по идее блок `page` — он, судя по неймингу, какой-то общий про раскладку ВСЕХ страниц сайта. Т.е. если представить, что у нас 10 разных страниц, будет странно пихать в него частную раскладку блоков разных страниц.

2020-12-18 11:17 UTC, merged