13. Доверстатm страницу формы
htmlacademy-adaptive/1005163-pognali-21 pull request #12
Opened 2020-12-24 10:02 UTC by iShangareev

2020-12-25 06:40 UTC, mikhin commented
Такое ощущение, что как-то не так происходит переключение по брейкпоинту между планшетной и десктопной версией:

<img width="1277" alt="Снимок экрана 2020-12-25 в 09 38 56" src="https://user-images.githubusercontent.com/38258318/103123372-2e8d0f80-4695-11eb-8780-be0c37ff76d7.png">
<img width="1279" alt="Снимок экрана 2020-12-25 в 09 39 38" src="https://user-images.githubusercontent.com/38258318/103123376-32209680-4695-11eb-92ae-42d634e26fbd.png">
<img width="1278" alt="Снимок экрана 2020-12-25 в 09 39 52" src="https://user-images.githubusercontent.com/38258318/103123378-32b92d00-4695-11eb-8d54-6026b50dafe0.png">

2020-12-25 07:01 UTC, mikhin requested changes

2020-12-25 07:01 UTC, mikhin commented on source/form.html
> +              <table class="calendar travel-card__calendar">
Лайк за всю разметку таблицы!

2020-12-25 07:01 UTC, mikhin commented on source/form.html
> +                    Чел.
Вот тут как раз по семантике `Чел`, кажется, должен идти после инпута, чтобы предложение по-русски читалось правильно.

2020-12-25 07:01 UTC, mikhin commented on source/form.html
> +                    Чел.
Но ща это необязательно

2020-12-25 07:01 UTC, mikhin commented on source/sass/blocks/alphabet-countries.scss
> +  display: none;
Блок не должен хотеть сам себя скрывать сразу

2020-12-25 12:41 UTC, iShangareev commented on source/sass/blocks/travel-card-direction.scss
> +    grid-template-columns: 1fr 1fr 1fr;
ну в пределах разумного все ок вниз растет

2020-12-25 12:41 UTC, iShangareev commented on source/sass/blocks/travel-card-direction.scss
> +    content: counter(section) ".";
Спасибо)

2020-12-25 12:42 UTC, iShangareev commented on source/sass/blocks/footer.scss
>    z-index: 5;
Окей, понял)

2020-12-25 12:45 UTC, iShangareev commented on source/sass/blocks/finish-step.scss
> +  .next-card-button .finish-step_big {
Вот так сидишь по пять часов чистого кодинга и начинаешь херню делать)) Вообще непонятно откуда это появилось, удалил эту нечисть

2020-12-25 13:01 UTC, iShangareev commented on source/sass/blocks/choosen-country.scss
> +    right: -90px;
Согласен, много ошибок допустил при верстке сейчас сделал бы подругому) Решил эту проблему тем что брекпойнт увеличил и макет не резинился

2020-12-25 13:11 UTC, iShangareev commented on source/sass/blocks/calendar.scss
> +.calendar__day_disabled {
Фэнкс)

2020-12-25 13:12 UTC, iShangareev commented on source/sass/blocks/alphabet-wrapper.scss
>      .alphabet-wrapper__list_big {
Эта бы косяк, исправил)

2020-12-25 13:17 UTC, iShangareev commented on source/form.html
> +                  class="travel-action-plan__title travel-action-plan__title_czech"
Понял, буду иметь ввиду спасибо, у меня часто возникают такие мысли в голове но от недостатка знаний в голове образуется коллапс)

2020-12-25 13:59 UTC, iShangareev commented on source/form.html
> +                        class="alphabet-wrapper__item alphabet-wrapper__item-selected"
тут меняется состояние элемента поменял на модификатор)

2020-12-25 13:59 UTC, iShangareev commented on source/form.html
> +              <table class="calendar travel-card__calendar">
Благодарствую)

2020-12-25 14:03 UTC, iShangareev commented on source/form.html
> +                    Чел.
Ок, понял оставлю так)

2020-12-25 14:07 UTC, iShangareev commented on source/sass/blocks/alphabet-countries.scss
> +  display: none;
Поправил)

2020-12-25 20:00 UTC, mikhin requested changes
Сейчас страница каталога у меня сломалась совсем
<img width="1275" alt="Снимок экрана 2020-12-25 в 23 00 10" src="https://user-images.githubusercontent.com/38258318/103141410-05a46300-4705-11eb-9536-3daa78ce0ff7.png">

2020-12-26 06:46 UTC, iShangareev commented on source/form.html
> +                  class="type-travel-list__link type-travel-list_fly"
Да, что то я совсем косячу))Исправил

2020-12-26 07:01 UTC, iShangareev commented on source/form.html
> +                        class="alphabet-wrapper__item alphabet-wrapper__item_selected"
Вот это вот очень правильно ты сказал, понял, принял исправил)

2020-12-26 16:07 UTC, merged