2. Разметка главной страницы
htmlacademy-adaptive/1005163-pognali-21 pull request #2
Opened 2020-11-16 09:09 UTC by iShangareev

2020-11-16 10:08 UTC, mikhin requested changes

2020-11-16 10:08 UTC, mikhin commented on source/index.html
> +        <h3 class="companion__title">Попутчики</h3>
Кажется, этот блок похож на `<p class="about__title">О сервисе</p>`

Значит мы можем выделить эту абстракцию в отдельный БЭМ-блок и переиспользовать его уже как минимум в двух местах)

2020-11-16 10:08 UTC, mikhin commented on source/index.html
> +        <div class="companion__card">
Давай выделим карточку из списка в отдельный БЭМ-блок?)

2020-11-16 10:08 UTC, mikhin commented on source/index.html
> +            <p class="companion__info-username">Таня Фирсова</p>
Это подзаголовок

2020-11-16 10:08 UTC, mikhin commented on source/index.html
> +            <div class="companion__info-tag">
Можно и отдельный БЭМ-блок бахнуть)

2020-11-16 10:08 UTC, mikhin commented on source/index.html
> +          <input type="submit" class="contacts__subscribe-button" />
Давай разметим как button

2020-11-16 10:08 UTC, mikhin commented on source/index.html
> +      <a class="footer__logo">
Это тянет на отдельный БЭМ-блок, т.к. можно переиспользовать в шапке. Отличия в дизайне и цветовых оттенках можно добавить через модификатор)

2020-11-16 12:25 UTC, iShangareev commented on source/index.html
> +          >ул. Большая Конюшенная, 19/8
Да, у меня претиер иногда так хулиганит

2020-11-16 15:01 UTC, iShangareev commented
Возможно я где-то снаркоманил, но вроде все ок)))

2020-11-17 08:00 UTC, mikhin requested changes

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <p class="navbar-menu__title">О сервисе Направления Попутчики</p>
@iShangareev, это должно быть меню и отдельные пункты)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <button class="navbar-menu__authorization button" type="button">
@iShangareev, это ссылка скорее)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +          <li class="navbar-menu__item">
@iShangareev, получилось что все элементы это как будто пункты меню навигации, судя по именованию. Но это не так. Соцсети, контакты, авторизация — не относятся к навигации. Давай поправим в следующем ПР?)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <ul class="navbar-menu__social-list">
@iShangareev, лучше сделать отдельный БЭМ-блок)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +              <button
@iShangareev, во-первых, кажется, что это скорее ссылка. Во-вторых, все интерактивные элементы должны иметь текстовое описание, даже если его нет в дизайн)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +          <ul class="step-list">
@iShangareev, 👍

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <li class="step-item">
Тут ща не по БЭМ: это должны быть элементы блока, а не отдельные БЭМ-блоки)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +      <section class="about">
Проблема осталась — по коду непонятно, что это за блок, для чего нужен и что делает)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +      <section class="direction">
Проблема осталась — по коду непонятно, что это за блок, для чего нужен и что делает)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +          <h2 class="direction__title">Направления</h2>
По идее это тоже блок `short-info`, только с модификатором темы, например. Типа `short-info_theme_light`

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <li class="direction-item">
Item звучит так как будто блок знает, что будет куда-то вложен, а не должен хотеть. Т.е. блок должен быть независимым. Лучше будет `direction-card`

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <li class="direction-item">
Тем более получается что по семантике БЭМ-блок это `li`, а значит его можно вложить только в `ul`, и такого тоже не должно быть)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <p class="short-info__quote">
А это не `short-info__text-important`?

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +      <section class="companion">
Проблема осталась — по коду непонятно, что это за блок, для чего нужен и что делает)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <div class="companion-card-level">
Тут нужно либо переназвать блок, чтоб в именовании блока не было явной привязки к другому блоку, либо сделать эту часть элементом вышестоящего блока.

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <div class="companion-card-level">
Плюс непонятно зачем этот блок сейчас нужен, если в нем лежат элементы от другого блока

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +              <ul class="companion-hashtags">
Тут нужно переназвать блок, чтоб в именовании блока не было явной привязки к другому блоку

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +              <ul class="companion-card__action-list">
Это скорее не actions, а interests

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +              <ul class="companion-card__action-list">
Можно тоже в отдельный БЭМ-блок)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +          <h2 class="visually-hidden">Зарегестрироваться</h2>
ЗарегИстрироваться

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +        <h2 class="visually-hidden">Тарифы для профиля</h2>
Предлагаю не мудрить со скрытыми заголовками, а назначать нужную семантику тем заголовкам что есть в дизайне)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +              <p class="rate__position">Вывод на первых позициях</p>
Этим элементам-абзацам не нужны разные классы, т.к. это все однотипные элементы списка

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +              <p class="rate__position-cost">99 руб./мес</p>
Лучше соотнести описание опции и цену в один элемент списка, иначе непонятно почему они равнозначно стоят в списке рядом друг с другом

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +            <label>
Нужное какое-то текстовое описание для лейбла

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +          class="company-logo-pic"
Это должен быть БЭМ-элемент, а не отдельный БЭМ-блок)

2020-11-17 08:00 UTC, mikhin commented on source/index.html
> +      <ul class="footer__social-list">
Лучше бахнуть отдельным БЭМ-блоком)

2020-11-17 12:57 UTC, mikhin approved these changes

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +            <h2 class="short-info__title short-info_theme_light__title">
Модификаторы используются чутка по-другому: уже в CSS ты можешь каскад использовать внутри модификатора и внутри БЭМ-блока:

```
.short-info_theme_light .short-info__title {
  color: #000;
}
```

Т.е. кинул модификатор на блок и в CSS через каскад задал нужные правила для элементов.

У элементов могут быть и свои модификаторы, но дублировать модификаторы блока на элементах не нужно.

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +                    class="type-travel-list__item-status type-travel-list__item-status_disabled"
Во, норм модификатор вообще! 👍

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +              <p class="rate__basic">Бесплатно</p>
Ага, уже лучше. И теперь осталось только переименовать в `rate__item-content` например. Сейчас получается что класс в CSS зависит от содержимого, т.е. если добавится еще 500 пунктов, надо будет для каждого придумать класс и продублировать стили.

Имена классов должны составляться прежде всего из терминов нашей с тобой профессиональной области — разработки интерфейсов, а потом уже можно подмешивать термины из бизнес области.

https://github.com/yoksel/common-words

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +            <label aria-label="поле ввода для почты">
Давай добавим текст внутрь и спрячем его за visually-hidden? Либо можно потом будет бахнуть на класс в стилях font-size: 0;.

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +            <label aria-label="поле ввода для почты">
Не хватает имени класса по БЭМ

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +                aria-label="кнопка позвонить нам"
Давай добавим текст внутрь и спрячем его за visually-hidden? Либо можно потом будет бахнуть на класс в стилях font-size: 0;.

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +              <a
Не хватает имени класса по БЭМ

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +        <li class="social-list__item social-list__item_theme_yellow">
Тоже о чем написал ранее — модификатор надо перенести один раз на блок и все, убрать с элементов. А потом уже через каскад бахнуть нужные стили на пункты)

2020-11-17 12:57 UTC, mikhin commented on source/index.html
> +            <li class="navbar-menu-navigation__item">О сервисе</li>
Нужны ссылки еще тут

2020-11-17 12:57 UTC, mikhin approved these changes

2020-11-17 12:58 UTC, mikhin commented on source/index.html
> +            <li class="navbar-menu-navigation__item">О сервисе</li>
А, уже есть, вижу

2020-11-17 12:58 UTC, merged