3. Разметка страницы формы
htmlacademy-adaptive/1005163-pognali-21 pull request #3
Opened 2020-11-18 12:53 UTC by iShangareev

2020-11-18 14:40 UTC, mikhin requested changes

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +    <header class="header">
Менюшка в хедере куда-то пропала, она должна быть на всех страницах)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +      <section class="companion-card companion-card_profile">
Вот тут лучше сразу родить отдельный блок и пока что, раньше времени, не пытаться оптимизировать БЭМ-блоки. Очевидно, по дизайну, что это разные блоки с разной целью употребления, так и давай их зафигачим разными и облегчим себе жизнь =)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +        <a href="" class="change-photo-button">Cменить фото</a>
Это скорее кнопка, т.к. либо будет вызван системный диалог загрузки файла (тогда вообще нужна форма тут), либо будет что-то еще на JS. Именно тут ссылаться в принципе некуда) Можно пока без формы, просто бахнуть кнопку)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +          <textarea name="hashtags" cols="30" rows="10">
Не, это не поле для ввода, а просто список, как был и на главной странице в карточках. Просто дизайн такой 😅

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +          <p class="companion-card__hashtags-title">ТЭГИ</p>
Нужно написать с большой буквы и строчными и стилизацию накинуть потом в CSS)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +          <p class="companion-card__transport-title">Транспорт</p>
Это и «ТЭГИ» похожи на подзаголовки)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +          <li class="user-travel-plan__direction">
Давай карточку сделаем отдельном БЭМ-блоком)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +            <p class="user-travel-plan__direction-country">
Это подзаголовок)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +              1. Франция, Италия
Тут ваще бы по красоте счетчик вынести из HTML в CSS. Потому что ща похоже что это просто как псевдо-элемент или маркер списка)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +            <a href="" class="user-travel-plan__direction-change">изменить</a>
С большой буквы)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +              <button class="travel-duration__button-minus"></button
Вот тут как раз тот случай, когда кнопки в обоих инпутах одинаковые (и сами инпуты тоже), поэтому это должен быть один и тот же БЭМ-блок, а не разные и именован он должен быть не исходя из бизнес-терминов (попутчики, длительность), а исходя из своего функционального назначения (кнопка, инпут, поле формы).

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +              class="children-allow"
Тут тоже нейминг лучше сделать исходя из функионального назначения, а не из бизнеса

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +            <label for="children-allow">Можно с детьми</label>
Нужен класс

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +            <input class="travel-calendar" type="date" name="calendar" />
Календарь нужно верстать, кажется, это не системный календарь.

Глянешь в ТЗ?

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +            <a href="" class="next-step button">Следующий шаг</a>
next-step непонятный класс

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +              <p class="choosen-country__name">Босния и герцеговина</p>
Кажется, что элемент <select>

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +              <span class="choosen-country__flag"></span>
Не хватает еще кнопки удаления

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +            <a href="" class="previus-step">Yа шаг назад</a>
Опечатка

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +                cols="30"
Это лучше убрать и стилизовать размер через CSS)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +            <p class="travel-card__title">Шаг 3. Развлечения</p>
Это заголовок, даже судя по имени класса 😅

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +            <div class="travel-card__action-plan">
Лучше в отдельный БЭМ-блок)

2020-11-18 14:40 UTC, mikhin commented on source/form.html
> +      <ul class="social-list social-list_theme_yellow">
Лайк за модификатор 👍

2020-11-18 14:40 UTC, mikhin commented on source/index.html
> +                >кнопка позвонить нам</a
Форматирование съехало

2020-11-18 14:40 UTC, mikhin commented on source/index.html
> +
Лишняя строка)

2020-11-19 06:11 UTC, iShangareev commented on source/form.html
> +          <textarea name="hashtags" cols="30" rows="10">
Я тут глянул, в тех задании так написали, поэтому так сделал вот ссыль https://prnt.sc/vlxhcr

2020-11-19 06:47 UTC, iShangareev commented on source/form.html
> +            <input class="travel-calendar" type="date" name="calendar" />
https://prnt.sc/vlxzon да, ты прав)

2020-11-19 07:41 UTC, iShangareev commented on source/form.html
> +              <p class="choosen-country__name">Босния и герцеговина</p>
кажется что то не дописал)

2020-11-19 08:06 UTC, mikhin approved these changes

2020-11-19 08:06 UTC, mikhin commented on source/form.html
> +          <textarea name="hashtags" cols="30" rows="10">
А, сорри, ты прав!

2020-11-19 08:06 UTC, mikhin commented on source/form.html
> +            <label class="checkbox-allow-name" for="children-allow"
Непонятно почему инпут и лейбл это два разных БЭМ-блока

2020-11-19 08:06 UTC, mikhin commented on source/form.html
> +                <li class="calendar__day calendar__day-active">26</li>
Модификаторы по-другому пишутся

2020-11-19 08:06 UTC, mikhin commented on source/form.html
> +                  <li class="prev-month"></li>
Если тут лежат баттонс, то нужно сразу кнопки и разметить

2020-11-19 08:06 UTC, mikhin commented on source/form.html
> +                    Март<span class="calendar__year"></span>2019</span>
Опечатка в разметке

2020-11-19 08:06 UTC, mikhin commented on source/form.html
> +                <li class="calendar__day">1</li>
Наверняка в них можно тыкать и что-то будет делаться, значит это кнопки или ссылки)

2020-11-19 08:06 UTC, mikhin commented on source/form.html
> +            <a href="" class="previus-card">Шаг назад</a>
Опечатка в имени класса)

2020-11-19 08:06 UTC, merged