10. Адаптивная сетка для главной страницы
htmlacademy-adaptive/1005163-pognali-21 pull request #8
Opened 2020-11-28 07:31 UTC by iShangareev

2020-11-29 12:10 UTC, mikhin requested changes

2020-11-29 12:10 UTC, mikhin commented on source/index.html
> +          <div class="short-info short-info_companion">
Зачем нужен модификатор?

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/button-detail.scss
> +@media (min-width: $mobile-width-only) {
Не хватает отступа

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/button-detail.scss
> +@media (min-width: $mobile-width-only) {
А расскажи зачем нужно именно `only`?

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/companion-card.scss
> +@media (min-width: $tablet-width) {
Давай везде добавим вертикальный отступ в одну строку (во всех файлах) и больше не пишу)

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/companion-travel.scss
> +  .companion-travel .page-margin {
Не должны хотеть использовать «межблочный каскад» — когда стили одного БЭМ-блока влияют на стили другого БЭМ-блока. Должны хотеть строить абстракции таким образом, чтобы вся необходимая функциональность была выстроена в терминах одного БЭМ-блока.

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/direction-card.scss
> +    order: -1;
О, это интересно. А зачем?)

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/direction-travel.scss
> +      "direction-card-2 short-info_theme_light"
> Не должны хотеть использовать «межблочный каскад» — когда стили одного БЭМ-блока влияют на стили другого БЭМ-блока. Должны хотеть строить абстракции таким образом, чтобы вся необходимая функциональность была выстроена в терминах одного БЭМ-блока.

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/menu-box.scss
> +    padding: 26px;
Оч странный отступ)

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/menu-box.scss
> +    padding: 40px;
И здесь тоже =) Может это внешний отступ на самом деле? Который нужно повесить на микс?

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/navbar-menu-navigation.scss
> +    display: none;
БЭМ-блок не должен хотеть скрывать сам себя изначально. Если он должен быть скрытым, это нужно сделать через модификатор (функционально названный, а не прибитый к месту употребления) или через микс.

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/navbar-menu.scss
> +.navbar-menu__item:nth-child(1) {
Непонятно что это значит, лучше докинуть еще класс, микс или модификатор

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/navbar.scss
> +    margin: 0 26px;
На блоке не должно быть свойств, описывающих внешнюю геометрию)

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/navbar.scss
> +    margin: 0 40px;
На блоке не должно быть свойств, описывающих внешнюю геометрию)

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/page-margin.scss
> +  margin: 0 25px;
Это паддинги)

2020-11-29 12:10 UTC, mikhin commented on source/sass/blocks/promo-board.scss
> +  .promo-board .page-margin {
Не должны хотеть использовать «межблочный каскад» — когда стили одного БЭМ-блока влияют на стили другого БЭМ-блока. Должны хотеть строить абстракции таким образом, чтобы вся необходимая функциональность была выстроена в терминах одного БЭМ-блока.

2020-11-29 12:10 UTC, mikhin commented on source/sass/style.scss
> +$mobile-width-only: 320px;
А, я понял. Но такого мы не должны хотеть. Мы же используем min-width, а значит стили описанные по умолчанию, без медиа-выражения, это и есть `mobile-only` =)

2020-11-30 06:29 UTC, iShangareev commented on source/index.html
> +          <nav class="navbar-menu-navigation navbar-menu-navigation_desktop">
В десктопной версии появляется меню навигации https://prnt.sc/vsm8ik, что бы не создавать новый бэм блок я использую уже существующий из мобильного меню https://prnt.sc/vsm90j, но там разные стили поэтому я добавляю модификатор и использую его в двух местах. Я так понимаю правильнее создать новый БЭМ блок  для десктопной версии https://prnt.sc/vsm8ik?

2020-11-30 06:36 UTC, iShangareev commented on source/index.html
> +          <ul class="promo-board-list promo-board-list_header">
Окей, понял, а когда тогда поступить в данном случае? Создать вообще новый бэм блок или дописать класс к существующему https://prnt.sc/vsmded или как?)

2020-11-30 06:42 UTC, iShangareev commented on source/index.html
> +          <div class="short-info short-info_companion">
Здесь видимо я что то хотел сделать но потом передумал, удалил)

2020-11-30 06:53 UTC, iShangareev commented on source/sass/blocks/button-detail.scss
> +@media (min-width: $mobile-width-only) {
Так в демке было, просто скопипастил)

2020-11-30 07:16 UTC, iShangareev commented on source/sass/blocks/direction-card.scss
> +    order: -1;
Здесь строка местами меняется по макету https://prnt.sc/vsmyx7 джунгли зовут по списку в мобильной версии идут последним а в планшетной версии идет по списку вторым

2020-11-30 07:45 UTC, iShangareev commented on source/sass/blocks/direction-travel.scss
> +      "direction-card-2 short-info_theme_light"
А как тогда строить сетку, миксовать с другими классами?

2020-11-30 07:47 UTC, iShangareev commented on source/sass/blocks/menu-box.scss
> +    padding: 40px;
Не, эт внутренний отступ)

2020-11-30 10:33 UTC, iShangareev commented on source/sass/blocks/direction-travel.scss
> +      "direction-card-2 short-info_theme_light"
Замиксовать например direction-travel__descripton

2020-11-30 10:33 UTC, iShangareev commented on source/index.html
> +          <nav class="navbar-menu-navigation navbar-menu-navigation_desktop">
Названия делать исходя из функциональности

2020-11-30 10:39 UTC, iShangareev commented on source/sass/blocks/navbar-menu-navigation.scss
> +    display: none;
замиксовать от родительского блока

2020-11-30 10:44 UTC, iShangareev commented on source/sass/style.scss
> +$mobile-width-only: 320px;
перенести из медиа выражения в обычное состояние

2020-11-30 18:31 UTC, mikhin approved these changes

2020-11-30 18:31 UTC, mikhin commented on source/sass/blocks/companion-travel.scss
> +  .companion-travel__wrapper {
❤️

2020-11-30 18:31 UTC, merged