11. Адаптивная сетка для страницы формы
htmlacademy-adaptive/1005163-pognali-21 pull request #9
Opened 2020-12-02 07:27 UTC by iShangareev

2020-12-02 08:07 UTC, mikhin requested changes

2020-12-02 08:07 UTC, mikhin commented on source/form.html
> +      <div class="page-margin header__wrapper">
`wrapper`, `container` всегда не очень имена, т.к. ничего не говорят про элемент конкретного. Что за обертка? Как минимум можно использовать `content`

2020-12-02 08:07 UTC, mikhin commented on source/form.html
> +        <h2 class="header__title">Направления</h2>
Точно хедер должен хотеть залазить сюда своими элементами?

2020-12-02 08:07 UTC, mikhin commented on source/form.html
> +              alt="Погнали?"
не очень alt

2020-12-02 08:07 UTC, mikhin commented on source/form.html
> +              >8 800 555-86-28</a
форматирование кривоватое

2020-12-02 08:07 UTC, mikhin commented on source/form.html
> +            <a href="https://facebook.com" class="social-list__link"></a>
Не хватает текстовых описаний для интерактивных элементов

2020-12-02 08:07 UTC, mikhin commented on source/sass/blocks/calendar.scss
> +    order: 6;
БЭМ-блок не должен иметь стили внешней геометрии и хотеть сам себя выравнивать в контексте

2020-12-02 08:07 UTC, mikhin commented on source/sass/blocks/checkbox-allow.scss
> +    order: 4;
БЭМ-блок не должен иметь стили внешней геометрии и хотеть сам себя выравнивать в контексте

2020-12-02 08:07 UTC, mikhin commented on source/sass/blocks/next-card-button.scss
> +    order: 7;
БЭМ-блок не должен иметь стили внешней геометрии и хотеть сам себя выравнивать в контексте

2020-12-02 08:07 UTC, mikhin commented on source/sass/blocks/travel-duration.scss
> +    order: 5;
БЭМ-блок не должен иметь стили внешней геометрии и хотеть сам себя выравнивать в контексте

2020-12-02 08:19 UTC, iShangareev commented on source/form.html
> +        <h2 class="header__title">Направления</h2>
Думаю это более менее подходящий вариант здесь

2020-12-03 07:11 UTC, mikhin approved these changes

2020-12-03 07:11 UTC, mikhin commented on source/sass/blocks/alphabet-countries.scss
> +.alphabet-wrapper__list {
Нужен вертикальный отступ

2020-12-03 07:11 UTC, mikhin commented on source/sass/blocks/finish-step.scss
> +    width: 50%;
Интересно ширина блока зависит по дизайну прям от него самого или от контекста в котором он используется?

2020-12-03 07:11 UTC, mikhin commented on source/sass/blocks/header.scss
> +  .header__title {
Отступ

2020-12-03 07:11 UTC, mikhin commented on source/sass/blocks/travel-card.scss
> +  .travel-card__filter {
Странно, что проверка не падает. Можешь во всем проекте поправить такие вертикальные отступы?

2020-12-03 07:11 UTC, merged

2020-12-03 07:51 UTC, iShangareev commented on source/sass/blocks/finish-step.scss
> +    width: 50%;
От контекста все таки, добавил ему модификатор

2020-12-03 07:56 UTC, iShangareev commented on source/sass/blocks/travel-card.scss
> +  .travel-card__filter {
ок, поправлю